---
- name: Install package python3
  ansible.builtin.dnf:
    name: python3
    state: present

- name: Install package python3-virtualenv
  ansible.builtin.dnf:
    name: python3-virtualenv
    state: present

- name: Install package python3-pip
  ansible.builtin.dnf:
    name: python3-pip
    state: present
